---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "fennekin23"
  - package-ecosystem: "nuget"
    directory: "/"
    groups:
      minor-and-patch:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    schedule: 
      interval: weekly
    reviewers:
      - "fennekin23"
    