using System.Text;

namespace Fennekin23.BuilderGenerator.CodeBuilder;

public class SourceFileBuilder(StringBuilder builder)
{
    public void AddHeader()
    {
        builder.AppendLine(
            """
            //------------------------------------------------------------------------------
            // <auto-generated>
            //     This code was generated by the Fennekin23.BuilderGenerator source generator.
            //     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
            // </auto-generated>
            //------------------------------------------------------------------------------
            """);
    }

    public void EnableNullable() => builder.AppendLine("#nullable enable");

    public void AddNamespace(Action<NamespaceDefinitionBuilder>? buildNamespace)
    {
        if (buildNamespace is not null)
        {
            NamespaceDefinitionBuilder namespaceBuilder = new(0, builder);
            buildNamespace(namespaceBuilder);
        }
    }
}