using System.Text;

namespace Fennekin23.BuilderGenerator.CodeBuilder;

public class SourceFileBuilder(StringBuilder builder)
    : CodeBuilderBase(0, builder)
{
    private readonly StringBuilder _builder = builder;
    
    public void AddHeader()
    {
        AddComment(
            """
            //------------------------------------------------------------------------------
            // <auto-generated>
            //     This code was generated by the Fennekin23.BuilderGenerator source generator.
            //     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
            // </auto-generated>
            //------------------------------------------------------------------------------
            """);
    }

    public void EnableNullable() => AddRaw("#nullable enable");

    public NamespaceBuilder CreateNamespaceBuilder() => new(0, _builder);
}