//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Fennekin23.BuilderGenerator source generator.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Fennekin23.BuilderGenerator.Tests.Samples
{
    /// <summary>
    ///    Builder class for <see cref="Fennekin23.BuilderGenerator.Tests.Samples.SamplePublicPositionalRecord" />.
    /// </summary>
    public sealed class SamplePublicPositionalRecordBuilder
    {
        private String _stringproperty = default!;
        public SamplePublicPositionalRecordBuilder WithStringProperty(String value)
        {
            _stringproperty = value;
            return this;
        }
        private Int32 _intproperty = default!;
        public SamplePublicPositionalRecordBuilder WithIntProperty(Int32 value)
        {
            _intproperty = value;
            return this;
        }
        private Boolean _booleanproperty = default!;
        public SamplePublicPositionalRecordBuilder WithBooleanProperty(Boolean value)
        {
            _booleanproperty = value;
            return this;
        }
        private Int64 _longproperty = default!;
        public SamplePublicPositionalRecordBuilder WithLongProperty(Int64 value)
        {
            _longproperty = value;
            return this;
        }
        public Fennekin23.BuilderGenerator.Tests.Samples.SamplePublicPositionalRecord Build()
        {
            return
                new Fennekin23.BuilderGenerator.Tests.Samples.SamplePublicPositionalRecord
                (
                    StringProperty: _stringproperty,
                    IntProperty: _intproperty
                )
                {
                    BooleanProperty = _booleanproperty,
                    LongProperty = _longproperty
                };
        }
    }
}
