//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Fennekin23.BuilderGenerator source generator.
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Fennekin23.BuilderGenerator.Tests
{
    /// <summary>
    ///    Builder class for <see cref="Fennekin23.BuilderGenerator.Tests.SampleInternalPositionalClass" />.
    /// </summary>
    internal sealed partial class SampleInternalPositionalClassBuilder
    {
        private String _stringproperty = default!;
        public SampleInternalPositionalClassBuilder WithStringProperty(String value)
        {
            _stringproperty = value;
            return this;
        }
        private Int32 _intproperty = default!;
        public SampleInternalPositionalClassBuilder WithIntProperty(Int32 value)
        {
            _intproperty = value;
            return this;
        }
        private Boolean _booleanproperty = default!;
        public SampleInternalPositionalClassBuilder WithBooleanProperty(Boolean value)
        {
            _booleanproperty = value;
            return this;
        }
        private Int64 _longproperty = default!;
        public SampleInternalPositionalClassBuilder WithLongProperty(Int64 value)
        {
            _longproperty = value;
            return this;
        }
        public Fennekin23.BuilderGenerator.Tests.SampleInternalPositionalClass Build()
        {
            return
                new Fennekin23.BuilderGenerator.Tests.SampleInternalPositionalClass
                (
                    StringProperty: _stringproperty,
                    IntProperty: _intproperty
                )
                {
                    BooleanProperty = _booleanproperty,
                    LongProperty = _longproperty
                };
        }
    }
}
